### ISSUE TITLE
Error suez_water integration home assistant 2024.12.3

### ISSUE THREAD

**Issue by d4nm0** [jb101010-2/pySuez#11]
i switched to home assistant 2024.12.3 precisely for your integration to be able to add water consumption to the energy dashboard. The previous version was working and returning data. But with the new one, I've got an error and now I can't get any data back.

`2024-12-13 13:44:51.752 ERROR (MainThread) [homeassistant.core] Unexpected error fetching suez_water data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/suez_water/coordinator.py", line 80, in _async_update_data
    price=(await self._suez_client.get_price()).price,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pysuez/suez_client.py", line 257, in get_price
    return PriceResult(**json)
  File "/usr/local/lib/python3.13/site-packages/pysuez/models.py", line 80, in __init__
    self.price = float(price.replace(",", "."))
                       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
2024-12-13 13:44:55.818 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)
2024-12-13 13:44:55.820 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector (None)
2024-12-13 13:45:04.498 ERROR (MainThread) [homeassistant.core] Unexpected error fetching suez_water data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/suez_water/coordinator.py", line 80, in _async_update_data
    price=(await self._suez_client.get_price()).price,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pysuez/suez_client.py", line 257, in get_price
    return PriceResult(**json)
  File "/usr/local/lib/python3.13/site-packages/pysuez/models.py", line 80, in __init__
    self.price = float(price.replace(",", "."))
                       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
2024-12-13 13:45:10.774 ERROR (Recorder) [homeassistant] Error doing job: Unclosed client session (None)
2024-12-13 13:45:10.775 ERROR (Recorder) [homeassistant] Error doing job: Unclosed connector (None)
2024-12-13 13:45:22.640 ERROR (MainThread) [homeassistant.core] Unexpected error fetching suez_water data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/suez_water/coordinator.py", line 80, in _async_update_data
    price=(await self._suez_client.get_price()).price,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pysuez/suez_client.py", line 257, in get_price
    return PriceResult(**json)
  File "/usr/local/lib/python3.13/site-packages/pysuez/models.py", line 80, in __init__
    self.price = float(price.replace(",", "."))
                       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
2024-12-13 13:45:24.742 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)
2024-12-13 13:45:24.742 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector (None)`

**Comment by jb101010-2** [comment]
The problem is that I have added a new sensor for water price but you don't seem to have that information, could you check at
https://www.toutsurmoneau.fr/eau-dans-ma-commune if the price is defined.

For now the integration can't be used directly in energy dashboard, but a PR fixing that is under review. https://github.com/home-assistant/core/pull/131166#issue-comment-box

**Comment by d4nm0** [comment]
> The problem is that I have added a new sensor for water price but you don't seem to have that information, could you check at
> 
> https://www.toutsurmoneau.fr/eau-dans-ma-commune if the price is defined.
> 
> I'll try fixing it during the weekend.
> 
> 
> 
> For now the integration can't be used directly in energy dashboard, but a PR fixing that is under review. https://github.com/home-assistant/core/pull/131166#issue-comment-box


I dont a price for ma city here : https://www.toutsurmoneau.fr/eau-dans-ma-commune/

My city is "pannes 45700" maybe help for you test.

**Comment by jb101010-2** [comment]
``This is weird because when I contact the api with your city I got a price of 4.24, which is not displayed on the website but still available.

After login on the website, can you check if the inseeCode is available at this endpoint https://www.toutsurmoneau.fr/public-api/user/donnees-contrats, if possible give the output of the call but be careful to remove address and references.

If possible give the output in the following format
`
[
  {
    "name": "Domicile",
    "inseeCode": "42062",
    "brandCode": "SUEZ",
    "fullRefFormat": "-----redacted------",
    "fullRef": "-----redacted------",
    "addrServed": "-----redacted------",
    "isActif": true,
    "website-link": "-----redacted------",
    "searchData": "-----redacted------",
    "isCurrentContract": true,
    "codeSituation": 1
  }
]
`

**Comment by d4nm0** [comment]
```
[
   {
      "name":null,
      "inseeCode":"45247",
      "brandCode":"SUEZ",
      "fullRefFormat":"9x-8xxxxxxx0x09",
      "fullRef":"9xxxxxxxx09",
      "addrServed":"xxxxx 45700 PANNES",
      "isActif":true,
      "website-link":"\/mon-compte-en-ligne\/redirect?0=refClient\\u00xxxx1=9x-xxxxxx09",
      "searchData":" 9x-xxxx9 9xxxxxxxx0xxx09 xxxxx 45700 PANNES",
      "isCurrentContract":true,
      "codeSituation":1
   }
]
```

**Comment by jb101010-2** [comment]
Getting weirder, I don't see a failure reason in all your data.

If you have any knowlegde of python can you execute the proposed fix at:
- https://github.com/jb101010-2/pySuez/tree/fix_none-price
- python -m pysuez -u YOUR_LOGIN -p YOUR_PASSWORD -m test

Plus can you confirm, that you get a price value at https://www.toutsurmoneau.fr/information/donnee/price/45247
And can you also confirm that in the above request there was only one contract ?

**Comment by d4nm0** [comment]
https://www.toutsurmoneau.fr/information/donnee/price/45247 = {"price":"4,24"}
and here https://www.toutsurmoneau.fr/public-api/user/donnees-contrats just the json pasted above

**Comment by d4nm0** [comment]
/!\ change on my integration home assistant, I no longer have the error. I didn't change anything, I didn't even redo the configuration.

**Comment by jb101010-2** [comment]
Really weird, probably that Suez failed to give the price at the time.  
I'll plan a fix for an upcoming version to avoid the integration failing completely if it happens again.

**Comment by d4nm0** [comment]
great, is integration into the energy dashboard coming soon?

**Comment by jb101010-2** [comment]
Dev is ok on my side, I am waiting for reviews from the HA teams, but they are a bit underwhelmed at the moment.

If you want there an issue you can follow to give it a bump :smile: 
https://github.com/home-assistant/core/issues/107858
